### ISSUE TITLE
Identify datasets

### ISSUE THREAD

**Issue by Abbe98** [riksantikvarieambetet/Generous-Interface-Fashion#1]

**Comment by Ambrosiani** [comment]
Some Nordic Museum examples:

* [all shoes with an image](http://www.kringla.nu/kringla/sok?text=dräkt+skodon&filter=serviceOrganization%3Dnomu&filter=thumbnailExists%3Dj&filter=itemType%3Dobjekt/föremål) (K-samsök)
* [photos and objects from "Mitt 50-tal" exhibition](https://digitaltmuseum.se/search/?aq=exhibition%3A%2243F2E920-16A7-44A5-AF13-E5E57ED7F32A%22) (DiMu)

**Comment by Abbe98** [comment]
@Ambrosiani reaches out  to participating institutions.

**Comment by Ambrosiani** [comment]
photos and objects from "Mitt 50-tal" exhibition: https://github.com/riksantikvarieambetet/Generous-Interface-Fashion/blob/master/example_data/mitt-50-tal.json

**Comment by Ambrosiani** [comment]
"attire" ger 205 träffar från Östasiatiska: http://www.kringla.nu/kringla/sok?text=attire&filter=serviceOrganization%3Dsmvk-om&filter=thumbnailExists%3Dj

**Comment by Abbe98** [comment]
http://www.kringla.nu/kringla/sok?text=klädesplagg&filter=thumbnailExists%3Dj&filter=serviceOrganization%3Dsmvk-em&filter=serviceOrganization%3Dsmvk-om&filter=serviceOrganization%3Dsmvk-vkm

**Comment by Abbe98** [comment]
>Det ska vi försöka fixa till. Jag hoppas också att vi ska kunna bättra på en hel del av metadata.
>
>Vad är det för metadata som måste vara med? Beskrivning, sakord, datering, material (och en bild förstås)? Datering är det svåra för oss, saknas jätteofta men på ett mindre urval kommer vi kunna göra en insats.
>Funkar det med länkar till Kringla? Här är en där jag sökt på träsnitt dräkt på ÖM och EM:
http://www.kringla.nu/kringla/sok?text=tr%C3%A4snitt+dr%C3%A4kt&filter=serviceOrganization%3Dsmvk-em&filter=serviceOrganization%3Dsmvk-om&filter=thumbnailExists%3Dj&sida=2
>
>Just ett urval av träsnitt är något vi pratat om. 
>
>Här är dräkt, textil, asien på EM, säg gärna några exempel på objekt som ni tycker är tillräckligt bra:
http://www.kringla.nu/kringla/sok?sida=1&text=dr%C3%A4kt+textil+asien&filter=thumbnailExists%3Dj&filter=serviceOrganization%3Dsmvk-em&filter=itemType%3Dobjekt/f%C3%B6rem%C3%A5l&filter=itemType%3Dfoto
>
>Ser redan en hel del som behöver städas…
>
>Jag funderar också på om det skulle funka att vi helt enkelt använder ett bestämt/unikt itemKeyWord för objekt/foton som vi vill ha med? Då skulle vi kunna göra ett mer precist urval och utelämna objekt med dålig metadata. Det skulle väl vara ganska enkelt att hämta hem från k-samsök?

**Comment by Abbe98** [comment]
Continued in #14 and #15
