### ISSUE TITLE
inconsistent filter toggle behavior

### ISSUE THREAD

**Issue by Ambrosiani** [riksantikvarieambetet/Generous-Interface-Fashion#28]
even though the filter toggles start as red, everything is displayed. i.e. there is no difference between everything red and everything green. This is probably something that should be user tested to figure out what their expectations are.

**Comment by Abbe98** [comment]
Is this caused by the result not being resorted, aka the new items are just appended to the result view?

I think we might want to randomize the result after each filter change.

**Comment by Ambrosiani** [comment]
no, I meant this:

* strumpor green, byxor green: both are shown (intuitive)
* strumpor green, byxor red: strumpor is shown (intuitive)
* strumpor red, byxor green: byxor is shown (intuitive)
* strumpor red, byxor red: both are shown (maybe not intuitive, but we don't want to start with an empty list, and we probably want people to select rather than deselect as their first interaction)

…maybe it's no problem/the best solution already, I just want to test it with users and find out if we're missing something.

**Comment by Abbe98** [comment]
I see, it does make sense if one would deselect items instead. It not a large change at all.

**Comment by Ambrosiani** [comment]
from today's discussion: keep the current functionality but adjust presentation when selecting the first item
