### ISSUE TITLE
New color picker 

### ISSUE THREAD

**Issue by Abbe98** [riksantikvarieambetet/Generous-Interface-Fashion#35]
HTML slider based?

**Comment by Abbe98** [comment]
Needs some type of sorting, with both light and hue supported.

**Comment by Abbe98** [comment]
![20180618_141304_003](https://user-images.githubusercontent.com/2631719/41535872-24bc8dbc-7304-11e8-894b-aded6a44dc81.jpg)

**Comment by ziherl** [comment]
några tips här: https://www.alanzucconi.com/2015/09/30/colour-sorting/

**Comment by Abbe98** [comment]
@ziherl ja mycket bra exempel, har testat både step sorting och Hilbert sorting problemet är att de lösningarna är helt värdelösa då man också ska använda dem för att välja färg då en färg förekommer på så många olika ställen. 

I step sorting tillexempel återfinns svart på minst fyra ställen.

**Comment by Abbe98** [comment]
Started but continued in #36
