### ISSUE TITLE
Update object view to include more metadata 

### ISSUE THREAD

**Issue by Abbe98** [riksantikvarieambetet/Generous-Interface-Fashion#39]

**Comment by Ambrosiani** [comment]
Photographer
License
Keywords (which keywords?)
Location (which location?)
Date (which date?)

**Comment by Abbe98** [comment]
currently available licenses:
 http://creativecommons.org/licenses/by-nc-nd/2.5/
 http://creativecommons.org/licenses/by/2.5/

Keywords - awaiting such a filter
Photographer - not a single item does currently have a photographer defined in Europeana.
Location - possible the edmPlaceLabelLangAware value but Europeana is messing it up somehow.
Date - not available in Europeana for any of the current items.

Implementing license, institution, and location for now the other values should be investigated as part of #42
