### ISSUE TITLE
swipe doesn't work in mobile safari

### ISSUE THREAD

**Issue by Ambrosiani** [riksantikvarieambetet/Generous-Interface-Fashion#54]

**Comment by Ambrosiani** [comment]
the solution used in filtermenu.vue works in mobile safari & desktop safari. the ones used in app.vue & objectview.vue don't work in mobile safari & desktop safari.

**Comment by Abbe98** [comment]
I think that this has something todo with the `[Vue warn]: Error in directive hammer unbind hook: "TypeError: Cannot read property 'handler'` that appears in the console for modals

**Comment by Ambrosiani** [comment]
solution: swipe disabled everywhere :)
