### ISSUE TITLE
Trouble running server

### ISSUE THREAD

**Issue by malmomuseum** [riksantikvarieambetet/Generous-Interface-Fashion#70]
When I run the server it succeeds but then it doesn't open the URL, and if I open http://127.0.0.1:8080/ in a browser it informs me that:

> Firefox: "Firefox kan inte upprätta en anslutning till servern på 127.0.0.1:8080."

> Chrome: _"Webbplatsen kan inte nås 127.0.0.1 avvisade anslutningen.
> kontrollera anslutningen
> kontrollera proxyn och brandväggen
> ERR_CONNECTION_REFUSED"_

I'm using:

**Node v10.15.0
Python3.6.8
npm 6.9.0
git 2.22.0**

Here is the package.json it runs (Automatically generated with `npm init`)
```

{
  "name": "package",
  "version": "1.0.0",
  "description": "generous interface",
  "main": "index.js",
  "scripts": {
    "serve": "serve"
  },
  "author": "serve",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/riksantikvarieambetet/Generous-Interface-Fashion.git"
  },
  "bugs": {
    "url": "https://github.com/riksantikvarieambetet/Generous-Interface-Fashion/issues"
  },
  "homepage": "https://github.com/riksantikvarieambetet/Generous-Interface-Fashion#readme",
  "keywords": [
    "serve"
  ],
  "dependencies": {
    "package.json": "^2.0.1",
    "serve": "^11.0.2"
  },
  "devDependencies": {}
}
```

Here is how it looks when I run the server:

```
>  npm run serve
> 
> > package@1.0.0 serve /home/john
> > serve
> 
> 
>    ┌────────────────────────────────────────────────────┐
>    │                                                    
>    │   Serving!                                         
>    │                                                    
>    │   - Local:            http://localhost:5000        
>    │   - On Your Network:  http://10.███.███.███:5000   (redacted)
>    │                                                    
>    │   Copied local address to clipboard!  
```

**Comment by Abbe98** [comment]
@malmomuseum it seams like your server is running on http://127.0.0.1:5000/ and not http://127.0.0.1:8080/

**Comment by malmomuseum** [comment]
Thanks.

I started from the beginning on another computer and got it working.

**Comment by Abbe98** [comment]
Okey great, let me know if I can be of any help! (albin.larsson@raa.se)
